name: Tweeter Action
author: devigned
description: Simple action to send a tweet via an GitHub Action.
inputs:
  message:
    description: 'message you want to tweet'
    required: true
  token:
    description: 'token for GitHub api'
    required: true
outputs:
  errorMessage:
    description: 'if something went wrong, the error message'
  sentMessage:
    description: 'verycode score generated'
runs:
  using: docker
  image: Dockerfile
#  using: docker
#  image: docker://ghcr.io/the-gophers/go-action:1.0.0
  args:
    - --message
    - "${{ inputs.message }}"
    - --token
    - ${{ inputs.apiKey }}
